object Resources {
    val settingsJiraUrlHaeader: String = "Your company Jira url"
    val settingsTokenHeader: String = "Token used to authorize requests"
    val settingsTokenPlaceholder: String = "Enter token"
    val settingsSave: String = "Save"
    val settingsJiraEmailHeader: String = "User email used to authorize requests"
    val settingsJiraEmailPlaceholder: String = "Enter email"
    val settingsHeader: String = "Settings"
    val failedToCreateAccount: String = "Failed to create account"
    val enterLoginPassword: String = "Enter login and password to enter"
    val fillInAllFields: String = "Fill in all fields"
    val welcomeButtonLabel: String = "Start"
    val welcomeHeader: String = "Welcome to Compose browser sample app"
    val welcomeDescription: String = "Click button to start using demo app with real use case usage"
    val loginHeader: String = "Sign in"
    val loginLabel: String = "Enter login"
    val passwordLabel: String = "Enter password"
    val confirmPasswordLabel: String = "Confirm password"
    val loginButton: String = "Enter"
    val createAccountButton: String = "I'm new, create account"
    val rememberMe: String = "Remember me"
    val createAccountHeader: String = "Create account"
    val createButton: String = "Create"
    val homeWelcomeHeader: String = "Welcome"
    val homeLogOutButton: String = "Log out"
}